import type { AppId, DomMutation, NodeId } from "../core/protocol.ts";
import { createNodeId } from "../core/protocol.ts";
import type { SyncChannel } from "../core/sync-channel.ts";
import { VirtualCommentNode, VirtualElement, VirtualTextNode } from "./element.ts";
import { VirtualEvent } from "./events.ts";
import { MutationCollector } from "./mutation-collector.ts";
import { querySelectorAll as selectorQueryAll, querySelector as selectorQuery } from "./selector-engine.ts";

let nodeCounter = 0;

function nextNodeId(prefix: string): NodeId {
	nodeCounter++;
	return createNodeId(`${prefix}-${nodeCounter}`);
}

/**
 * Virtual Document that exists in a worker thread.
 * All DOM mutations are recorded and batched via MutationCollector.
 */
export class VirtualDocument {
	readonly body: VirtualElement;
	readonly head: VirtualElement;
	readonly documentElement: VirtualElement;
	readonly nodeType = 9;
	readonly nodeName = "#document";

	readonly collector: MutationCollector;

	_defaultView: unknown = null;
	_syncChannel: SyncChannel | null = null;

	private _ids = new Map<string, VirtualElement>();
	private _listenerMap = new Map<string, (e: unknown) => void>();

	constructor(appId: AppId) {
		this.collector = new MutationCollector(appId);

		// Create structural elements without emitting mutations (they map to existing DOM)
		this.documentElement = new VirtualElement("HTML", this.collector, createNodeId("async-html"));
		this.head = new VirtualElement("HEAD", this.collector, createNodeId("head-node"));
		this.body = new VirtualElement("BODY", this.collector, createNodeId("body-node"));

		this.documentElement._ownerDocument = this;
		this.head._ownerDocument = this;
		this.body._ownerDocument = this;

		this.documentElement.appendChild(this.head);
		this.documentElement.appendChild(this.body);

		// Drain any mutations generated by structural setup
		this.collector.flush();
	}

	createElement(tag: string): VirtualElement {
		const id = nextNodeId("a");
		const element = new VirtualElement(tag, this.collector, id);
		element._ownerDocument = this;
		this._ids.set(id, element);

		const mutation: DomMutation = {
			action: "createNode",
			id,
			tag: element.tagName,
			textContent: "",
		};
		this.collector.add(mutation);
		return element;
	}

	createElementNS(_ns: string, tag: string): VirtualElement {
		return this.createElement(tag);
	}

	createTextNode(text: string): VirtualTextNode {
		const id = nextNodeId("t");
		const node = new VirtualTextNode(text, id, this.collector);
		node._ownerDocument = this;

		const mutation: DomMutation = {
			action: "createNode",
			id,
			tag: "#text",
			textContent: text,
		};
		this.collector.add(mutation);
		return node;
	}

	createComment(text: string): VirtualCommentNode {
		const id = nextNodeId("c");
		const node = new VirtualCommentNode(text, id, this.collector);
		node._ownerDocument = this;

		const mutation: DomMutation = {
			action: "createComment",
			id,
			textContent: text,
		};
		this.collector.add(mutation);
		return node;
	}

	createDocumentFragment(): VirtualElement {
		// Document fragments are lightweight elements that don't emit create mutations
		const frag = new VirtualElement("#document-fragment", this.collector, nextNodeId("f"));
		frag._ownerDocument = this;
		return frag;
	}

	getElementById(id: string): VirtualElement | null {
		return this._ids.get(id as NodeId) ?? null;
	}

	// Event listener routing
	addEventListener(name: string, callback: (e: unknown) => void): void {
		if (!name) return;
		const listenerId = `document_${name}_${Date.now()}`;
		this._listenerMap.set(listenerId, callback);
		const mutation: DomMutation = {
			action: "addEventListener",
			id: createNodeId("document"),
			name,
			listenerId,
		};
		this.collector.add(mutation);
	}

	removeEventListener(_name: string, callback: (e: unknown) => void): void {
		for (const [listenerId, cb] of this._listenerMap.entries()) {
			if (cb === callback) {
				this._listenerMap.delete(listenerId);
				const mutation: DomMutation = {
					action: "removeEventListener",
					id: createNodeId("document"),
					listenerId,
				};
				this.collector.add(mutation);
				break;
			}
		}
	}

	/**
	 * Route an event from the main thread to the appropriate listener.
	 * Resolves serialized target IDs to actual VirtualElement references.
	 */
	dispatchEvent(listenerId: string, event: unknown): void {
		const evt = event as Record<string, unknown>;
		// Resolve event target references from string IDs to VirtualElement refs
		if (typeof evt.target === "string") {
			evt.target = this._ids.get(evt.target as NodeId) ?? null;
		}
		if (typeof evt.currentTarget === "string") {
			evt.currentTarget = this._ids.get(evt.currentTarget as NodeId) ?? null;
		}
		if (typeof evt.relatedTarget === "string") {
			evt.relatedTarget = this._ids.get(evt.relatedTarget as NodeId) ?? null;
		}

		// Create VirtualEvent for bubbling support
		const virtualEvent = new VirtualEvent(evt.type as string, evt);

		// Sync input state from event to target element
		const targetEl = virtualEvent.target;
		if (targetEl && typeof targetEl === "object" && "_updateInputState" in targetEl) {
			const inputState: { value?: string; checked?: boolean; selectedIndex?: number } = {};
			if (evt.value !== undefined) inputState.value = evt.value as string;
			if (evt.checked !== undefined) inputState.checked = evt.checked as boolean;
			if (evt.selectedIndex !== undefined) inputState.selectedIndex = evt.selectedIndex as number;
			if (Object.keys(inputState).length > 0) {
				(targetEl as { _updateInputState: (s: typeof inputState) => void })._updateInputState(inputState);
			}
		}

		// Check document-level listeners first
		const docListener = this._listenerMap.get(listenerId);
		if (docListener) {
			docListener(virtualEvent);
			return;
		}

		// Find the element that owns this listener and dispatch to ALL its listeners for this event type
		let targetElement: VirtualElement | null = null;
		for (const el of this._ids.values()) {
			const listener = el.getEventListener(listenerId);
			if (listener) {
				targetElement = el;
				break;
			}
		}

		if (targetElement) {
			virtualEvent.currentTarget = targetElement;
			targetElement._dispatchBubbledEvent(virtualEvent);

			// Bubble up through parent chain if event bubbles
			if (virtualEvent.bubbles && !virtualEvent.propagationStopped) {
				let current = targetElement.parentNode;
				while (current && !virtualEvent.propagationStopped) {
					virtualEvent.currentTarget = current;
					current._dispatchBubbledEvent(virtualEvent);
					if (virtualEvent.propagationStopped) break;
					current = current.parentNode;
				}
			}
		}
	}

	/**
	 * Register an element so it can be found by getElementById.
	 */
	registerElement(id: string, element: VirtualElement): void {
		this._ids.set(id, element);
	}

	/**
	 * Register an element by its user-visible id attribute (distinct from internal NodeId).
	 */
	registerElementById(id: string, element: VirtualElement): void {
		this._ids.set(id, element);
	}

	/**
	 * Unregister an element by its user-visible id attribute.
	 */
	unregisterElementById(id: string): void {
		this._ids.delete(id);
	}

	querySelector(selector: string): VirtualElement | null {
		if (selector.startsWith("#")) {
			const found = this.getElementById(selector.slice(1));
			if (found) return found;
		}
		return selectorQuery(this.body, selector) ?? selectorQuery(this.head, selector);
	}

	querySelectorAll(selector: string): VirtualElement[] {
		return [...selectorQueryAll(this.head, selector), ...selectorQueryAll(this.body, selector)];
	}

	getElementsByTagName(tagName: string): VirtualElement[] {
		const upper = tagName.toUpperCase();
		return this.querySelectorAll(upper === "*" ? "*" : tagName);
	}

	getElementsByClassName(className: string): VirtualElement[] {
		const selector = className.split(/\s+/).filter(Boolean).map(c => `.${c}`).join("");
		return this.querySelectorAll(selector);
	}

	get defaultView(): unknown {
		return this._defaultView;
	}

	get ownerDocument(): VirtualDocument {
		return this;
	}
}
