import type { AppId, DomMutation, NodeId } from "../core/protocol.ts";
import {
	BODY_NODE_ID,
	createNodeId,
	DOCUMENT_NODE_ID,
	HEAD_NODE_ID,
	HTML_NODE_ID,
} from "../core/protocol.ts";
import type { SyncChannel } from "../core/sync-channel.ts";
import {
	VirtualCommentNode,
	VirtualElement,
	type VirtualNode,
	VirtualTextNode,
} from "./element.ts";
import { VirtualEvent } from "./events.ts";
import { MutationCollector } from "./mutation-collector.ts";
import {
	querySelector as selectorQuery,
	querySelectorAll as selectorQueryAll,
} from "./selector-engine.ts";

/**
 * Virtual Document that exists in a worker thread.
 * All DOM mutations are recorded and batched via MutationCollector.
 */
export class VirtualDocument {
	readonly body: VirtualElement;
	readonly head: VirtualElement;
	readonly documentElement: VirtualElement;
	readonly nodeType = 9;
	readonly nodeName = "#document";

	readonly collector: MutationCollector;

	_defaultView: unknown = null;
	_syncChannel: SyncChannel | null = null;

	private _ids = new Map<string, VirtualElement>();
	private _nodeIdToElement = new Map<NodeId, VirtualElement>();
	private _listenerMap = new Map<string, (e: unknown) => void>();
	private _listenerToElement = new Map<string, VirtualElement>();
	private _listenerCounter = 0;

	constructor(appId: AppId) {
		this.collector = new MutationCollector(appId);

		// Create structural elements without emitting mutations (they map to existing DOM)
		this.documentElement = new VirtualElement("HTML", this.collector, HTML_NODE_ID);
		this.head = new VirtualElement("HEAD", this.collector, HEAD_NODE_ID);
		this.body = new VirtualElement("BODY", this.collector, BODY_NODE_ID);

		this.documentElement._ownerDocument = this;
		this.head._ownerDocument = this;
		this.body._ownerDocument = this;

		this.documentElement.appendChild(this.head);
		this.documentElement.appendChild(this.body);

		// Drain any mutations generated by structural setup
		this.collector.flush();
	}

	createElement(tag: string): VirtualElement {
		const id = createNodeId();
		const element = new VirtualElement(tag, this.collector, id);
		element._ownerDocument = this;
		this._nodeIdToElement.set(id, element);

		const mutation: DomMutation = {
			action: "createNode",
			id,
			tag: element.tagName,
			textContent: "",
		};
		this.collector.add(mutation);
		return element;
	}

	createElementNS(ns: string, tag: string): VirtualElement {
		const el = this.createElement(tag);
		el._setNamespaceURI(ns);
		return el;
	}

	createTextNode(text: string): VirtualTextNode {
		const id = createNodeId();
		const node = new VirtualTextNode(text, id, this.collector);
		node._ownerDocument = this;

		const mutation: DomMutation = {
			action: "createNode",
			id,
			tag: "#text",
			textContent: text,
		};
		this.collector.add(mutation);
		return node;
	}

	createComment(text: string): VirtualCommentNode {
		const id = createNodeId();
		const node = new VirtualCommentNode(text, id, this.collector);
		node._ownerDocument = this;

		const mutation: DomMutation = {
			action: "createComment",
			id,
			textContent: text,
		};
		this.collector.add(mutation);
		return node;
	}

	createDocumentFragment(): VirtualElement {
		// Document fragments are lightweight elements that don't emit create mutations
		const frag = new VirtualElement("#document-fragment", this.collector, createNodeId());
		frag._ownerDocument = this;
		return frag;
	}

	getElementById(id: string): VirtualElement | null {
		return this._ids.get(id) ?? null;
	}

	// Event listener routing
	addEventListener(name: string, callback: (e: unknown) => void): void {
		if (!name) return;
		const listenerId = `document_${name}_${++this._listenerCounter}`;
		this._listenerMap.set(listenerId, callback);
		const mutation: DomMutation = {
			action: "addEventListener",
			id: DOCUMENT_NODE_ID,
			name,
			listenerId,
		};
		this.collector.add(mutation);
	}

	removeEventListener(_name: string, callback: (e: unknown) => void): void {
		for (const [listenerId, cb] of this._listenerMap.entries()) {
			if (cb === callback) {
				this._listenerMap.delete(listenerId);
				const mutation: DomMutation = {
					action: "removeEventListener",
					id: DOCUMENT_NODE_ID,
					listenerId,
				};
				this.collector.add(mutation);
				break;
			}
		}
	}

	/**
	 * Route an event from the main thread to the appropriate listener.
	 * Resolves serialized target IDs to actual VirtualElement references.
	 */
	private _resolveTarget(value: unknown): VirtualElement | null {
		if (typeof value === "number") {
			return this._nodeIdToElement.get(value as NodeId) ?? null;
		}
		if (typeof value === "string") {
			// Try parsing as number first (serialized numeric ID)
			const num = Number(value);
			if (!Number.isNaN(num)) {
				return this._nodeIdToElement.get(num as NodeId) ?? null;
			}
			// Fall back to user-visible id attribute lookup
			return this._ids.get(value) ?? null;
		}
		return null;
	}

	dispatchEvent(listenerId: string, event: unknown): void {
		const evt = event as Record<string, unknown>;
		// Resolve event target references from NodeIds to VirtualElement refs
		if (evt.target != null && typeof evt.target !== "object") {
			evt.target = this._resolveTarget(evt.target);
		}
		if (evt.currentTarget != null && typeof evt.currentTarget !== "object") {
			evt.currentTarget = this._resolveTarget(evt.currentTarget);
		}
		if (evt.relatedTarget != null && typeof evt.relatedTarget !== "object") {
			evt.relatedTarget = this._resolveTarget(evt.relatedTarget);
		}

		// Create VirtualEvent for bubbling support
		const virtualEvent = new VirtualEvent(evt.type as string, evt);

		// Sync input state from event to target element
		const targetEl = virtualEvent.target;
		if (targetEl && typeof targetEl === "object" && "_updateInputState" in targetEl) {
			const inputState: { value?: string; checked?: boolean; selectedIndex?: number } = {};
			if (evt.value !== undefined) inputState.value = evt.value as string;
			if (evt.checked !== undefined) inputState.checked = evt.checked as boolean;
			if (evt.selectedIndex !== undefined) inputState.selectedIndex = evt.selectedIndex as number;
			if (Object.keys(inputState).length > 0) {
				(targetEl as { _updateInputState: (s: typeof inputState) => void })._updateInputState(
					inputState,
				);
			}
		}

		// Check document-level listeners first
		const docListener = this._listenerMap.get(listenerId);
		if (docListener) {
			docListener(virtualEvent);
			return;
		}

		// O(1) lookup of the element that owns this listener
		const targetElement = this._listenerToElement.get(listenerId) ?? null;

		if (targetElement) {
			virtualEvent.currentTarget = targetElement;
			targetElement._dispatchBubbledEvent(virtualEvent);

			// Bubble up through parent chain if event bubbles
			if (virtualEvent.bubbles && !virtualEvent.propagationStopped) {
				let current = targetElement.parentNode;
				while (current && !virtualEvent.propagationStopped) {
					virtualEvent.currentTarget = current;
					current._dispatchBubbledEvent(virtualEvent);
					if (virtualEvent.propagationStopped) break;
					current = current.parentNode;
				}
			}
		}
	}

	/**
	 * Register an element by its internal NodeId.
	 */
	registerElement(id: NodeId, element: VirtualElement): void {
		this._nodeIdToElement.set(id, element);
	}

	/**
	 * Unregister an element by its internal NodeId (called during cleanup on removal).
	 */
	unregisterElement(id: NodeId): void {
		this._nodeIdToElement.delete(id);
	}

	/**
	 * Register an element by its user-visible id attribute (distinct from internal NodeId).
	 */
	registerElementById(id: string, element: VirtualElement): void {
		this._ids.set(id, element);
	}

	/**
	 * Unregister an element by its user-visible id attribute.
	 */
	unregisterElementById(id: string): void {
		this._ids.delete(id);
	}

	/**
	 * Register a listener ID to its owning element for O(1) event dispatch.
	 */
	registerListener(listenerId: string, element: VirtualElement): void {
		this._listenerToElement.set(listenerId, element);
	}

	/**
	 * Unregister a listener ID (called on removeEventListener or element cleanup).
	 */
	unregisterListener(listenerId: string): void {
		this._listenerToElement.delete(listenerId);
	}

	createEvent(_type: string): Record<string, unknown> {
		return {
			type: "",
			initEvent(type: string, bubbles?: boolean, cancelable?: boolean) {
				this.type = type;
				this.bubbles = bubbles ?? false;
				this.cancelable = cancelable ?? false;
			},
			bubbles: false,
			cancelable: false,
			preventDefault() {},
			stopPropagation() {},
			stopImmediatePropagation() {},
		};
	}

	get activeElement(): VirtualElement {
		return this.body;
	}

	createRange(): unknown {
		const doc = this;
		return {
			createContextualFragment(_html: string) {
				return doc.createDocumentFragment();
			},
			setStart() {},
			setEnd() {},
			collapse() {},
			selectNodeContents() {},
			cloneRange() {
				return doc.createRange();
			},
		};
	}

	createTreeWalker(
		root: VirtualElement,
		_whatToShow?: number,
	): { currentNode: VirtualNode; nextNode(): VirtualNode | null } {
		const nodes: VirtualNode[] = [];
		function collect(node: VirtualNode) {
			nodes.push(node);
			if (node instanceof VirtualElement) {
				for (const child of node.childNodes) {
					collect(child);
				}
			}
		}
		collect(root);
		let idx = 0;
		return {
			currentNode: root,
			nextNode() {
				idx++;
				if (idx < nodes.length) {
					this.currentNode = nodes[idx];
					return nodes[idx];
				}
				return null;
			},
		};
	}

	querySelector(selector: string): VirtualElement | null {
		if (selector.startsWith("#")) {
			const found = this.getElementById(selector.slice(1));
			if (found) return found;
		}
		return selectorQuery(this.body, selector) ?? selectorQuery(this.head, selector);
	}

	querySelectorAll(selector: string): VirtualElement[] {
		return [...selectorQueryAll(this.head, selector), ...selectorQueryAll(this.body, selector)];
	}

	getElementsByTagName(tagName: string): VirtualElement[] {
		const upper = tagName.toUpperCase();
		return this.querySelectorAll(upper === "*" ? "*" : tagName);
	}

	getElementsByClassName(className: string): VirtualElement[] {
		const selector = className
			.split(/\s+/)
			.filter(Boolean)
			.map((c) => `.${c}`)
			.join("");
		return this.querySelectorAll(selector);
	}

	get defaultView(): unknown {
		return this._defaultView;
	}

	get ownerDocument(): VirtualDocument {
		return this;
	}

	toJSON(): unknown {
		return this._serializeNode(this.documentElement);
	}

	private _serializeNode(node: VirtualNode): unknown {
		if (node.nodeType === 3) {
			return { type: "text", id: node._nodeId, text: (node as VirtualTextNode).nodeValue };
		}
		if (node.nodeType === 8) {
			return { type: "comment", id: node._nodeId, text: (node as VirtualCommentNode).nodeValue };
		}
		const el = node as VirtualElement;
		const attrs: Record<string, string> = {};
		const a = el.attributes;
		for (let i = 0; i < a.length; i++) {
			const attr = a.item(i);
			if (attr) attrs[attr.name] = attr.value;
		}
		return {
			type: "element",
			id: el._nodeId,
			tag: el.tagName,
			...(Object.keys(attrs).length > 0 ? { attributes: attrs } : {}),
			...(el.className ? { className: el.className } : {}),
			children: el.childNodes.map((c) => this._serializeNode(c)),
		};
	}
}
